### ISSUE TITLE
/reply doesn't work

### ISSUE THREAD

**Issue by ZysticV2** [Everfall-Development/ef-issues#8]
/reply doesn't work I have tested it multiple people and nothing pops up for them or me 

https://github.com/user-attachments/assets/2ecaff25-58b3-4c34-959d-d851925e49f1

**Comment by jellyton255** [comment]
This feature only functions for leo, similarly to the respond to call button. This will all be trashed for ef-dispatch anyways once it comes, as this cannot be fixed due to it's script being encrypted.
